---
stages:
  - install
  - build
  - docs
  - publish

variables:
  NODE_VERSION: 20-alpine
  NODE_PACKAGE_MANAGER: pnpm
  NODE_LINT_COMMAND: lint
  NODE_TEST_COMMAND: test
  NODE_INSTALL_ARGS: --ignore-scripts
  GITHUB_STATUS_PROJECT: listr2/listr2
  SKIP_GIT_HOOKS: '1'

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/node-run.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/semantic-release.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-build-internal.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/github-status.gitlab-ci.yml

test:
  parallel:
    matrix:
      - NODE_VERSION: 20-alpine
      - NODE_VERSION: 18-alpine
      - NODE_VERSION: 16-alpine

typecheck-examples:
  stage: docs
  extends: .node-run
  variables:
    NODE_COMMAND_SCRIPT: example:build
  needs:
    - install
  dependencies:
    - install
  only:
    refs:
      - master
      - next
      - next-major
      - alpha
      - beta
      - rc

vuepress:
  stage: docs
  extends: .node-run
  variables:
    NODE_COMMAND_SCRIPT: docs:build
  artifacts:
    paths:
      - ./docs/.vuepress/dist
  needs:
    - install
  dependencies:
    - install
  only:
    refs:
      - master
      - next
      - next-major
      - alpha
      - beta
      - rc

docker-build-docs:
  stage: publish
  extends: .docker-build-internal
  variables:
    DOCKERFILE_NAME: Dockerfile
    DOCKERFILE_CONTEXT: ./docs
    DOCKER_IMAGE_INTERNAL_NAME: docs-listr2
    DOCKER_IMAGE_TAGS: latest
  needs:
    - vuepress
    - build
  dependencies:
    - vuepress
  only:
    refs:
      - master
      - next
      - next-major
      - alpha
      - beta
      - rc

semantic-release:
  stage: publish
  extends: .semantic-release
  needs:
    - build
    - lint
    - test
  dependencies:
    - build
